### ISSUE TITLE
Can I get the image Dominant color before its 'Downloaded from URL'

### ISSUE THREAD

**Issue by vicky1787** [pixelogik/ColorCube#12]
Hello Developer,

Really nice library may say appreciate your work on the algorithm implemented.

I have a query like google Image in Iphone is you Check , if you scroll very fast for the search images grid, the first time you see a background of the most dominent color and then the actual image.

I want to implement the same behaviour, hence Can you please recommend if this can be done in this library or any reference.

I dont want to download an image of 3MB then show the dominent color for the second and then actual image rather it should show the dominent color while loading and then the actual image.

Can you advice.

**Comment by pixelogik** [comment]
Hi there - really hard to understand that text, but I think I got it. 

There is no way that you can compute a dominant color before you have the image. The color is computed based on the colors in the image. 

If you somehow can download a much smaller version of the image beforehand, that would help. The average color of the smaller image (50x50 for example) would be very close to the actual one in the big image. Downscaling images before running the algorithm is in general idea a good idea. Not only for performance reasons, but also because of the aggregating nature of downscaling, which already does part of the summation step.
